### ISSUE TITLE
api generated by swaggerhub does not match api expected by go-centrifuge node

### ISSUE THREAD

**Issue by charleenfei** [centrifuge/gateway#442]
snake_case is always replaced by camelCase when the api is generated.

could be related to https://github.com/swagger-api/swagger-codegen/issues/9255

**Comment by rdinicut** [comment]
Did you try to use swagger hub?

**Comment by rdinicut** [comment]
I am not a colab on cent node but there is an option there. That how I used to do it as far as I remember

**Comment by rdinicut** [comment]
If not we can use the swagger-api/swagger-codegen directly

**Comment by rdinicut** [comment]
I think this is fixed no?
