### ISSUE TITLE
Add NFT ID to document list

### ISSUE THREAD

**Issue by denniswell** [centrifuge/gateway#474]
@denniswell commented on [Fri Jul 03 2020](https://github.com/centrifuge/tinlake-ui/issues/441)

In column NFT status, instead of showing "minted" when the NFT is successfully minted, we should show the NFT ID. Can be abbreviated with the ellipsis... Column header should be changed to "NFT Status/ID" then

**Comment by rdinicut** [comment]
@denniswell So in theory the Doc can have more nfts. So we just take the first one? We can do it but this forces us to complicate the code and it  can be a bug at some point just FYI. We have a list of nfts also in the doc view and Edit.

**Comment by denniswell** [comment]
Let's do a comma seperated list, in case there may be several NFTs on a document at some point
