### ISSUE TITLE
Improve login/password guidelines

### ISSUE THREAD

**Issue by denniswell** [centrifuge/gateway#486]
- Email for login shouldn't be case sensitive
- Require password restrictions
    - 8 - 32 characters long 
    - Include at least 3 of the following character types:
        - English alphabet uppercase letter (A-Z)
        - English alphabet lowercase letter (a-z)
        - Decimal digit number (0-9)
        - Special characters

**Comment by rdinicut** [comment]
@denniswell this is done do i just close it?  I am not in zenhub
