### ISSUE TITLE
After document creation from a template, documents are showing up as duplicates

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/gateway#580]

**Comment by philipstanislaus** [comment]
After several debugging iterations and other priorities pushing this issue back on my task list, I finally found the exact reason for this issue.

**Comment by philipstanislaus** [comment]
Fixed through #582 .

**Comment by philipstanislaus** [comment]
For context: the bug can randomly appear whenever there is more than one collaborator.

**Comment by denniswell** [comment]
Fixed
